### ISSUE TITLE
Using last version of Autofac failed on iOS

### ISSUE THREAD

**Issue by Jerome2606** [NowBI/Xamarin-Forms-Mobile-Template#3]
Hello,

Maybe you got already into this issue: https://github.com/autofac/Autofac/issues/864
I tried to migrate this template to netstandard Core project and successfully did it for Android but on iOS even if the build has succeeded and the ioc declaration is right (because it's running fine on Android), I got exception on the build() of ioc container.

Do you already come into this issue with the last version of Autofac ?

**Comment by RoboCafaz** [comment]
We have yet to work on DotNetStandard Xamarin applications. If you want to push up a fork of your conversion perhaps I can take a look at it and we can integrate it back into the project?

**Comment by Jerome2606** [comment]
I quickly update from my changes of this afternoon.

I didn't check on test projects. I mainly focus on making iOS working

**Comment by Jerome2606** [comment]
Ok I get it.

Switching to netstandard 2.0 have fix the issue with Autofac
This is on my last branch master in my fork
